name: Daily Stock Buy Alerts

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 07:30 AM IST (2:00 AM UTC)
  workflow_dispatch:     # allows manual trigger from GitHub too

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run the notifier script
        run: |
          python "News fetcher/news_fetcher.py"
