name: Run Daily

on:
  workflow_dispatch:  # 👈 This line allows manual trigger from GitHub UI
  schedule:
    - cron: '30 2 * * *'  # original daily schedule (2:30 AM UTC / 8:00 AM IST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r 'News fetcher/requirements.txt'

    - name: Run news fetcher
      run: |
        python 'News fetcher/news_fetcher.py'
