name: Daily Stock Sentiment Check

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 7:30 AM IST (2:00 UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download spaCy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Run Stock Notifier
      run: |
        python stock_notifier.py

